channel_targets:
  - tudat-team
channel_sources:
  - tudat-team, conda-forge, defaults
boost_cpp:
  - 1.85.0
python:
  - 3.9
  - 3.10
  - 3.11
python_impl:
  - cpython
  - cpython
  - cpython
numpy:
  - 1.25.*
  - 1.25.*
  - 1.25.*
is_python_min:
  - 3.9
  - 3.10
  - 3.11  
c_compiler:
  - clang
c_compiler_version:
  - 18
cxx_compiler:
  - clangxx
cxx_compiler_version:
  - 18
