#python:
#  - 3.6
#  - 3.7
#  - 3.8
numpy:
  - 1.21
boost_cpp:
  - 1.72
channel_targets:
  - tudat-team dev
channel_sources:
  - tudat-team/label/dev, tudat-team, conda-forge, defaults
ignore_build_only_deps:
  - numpy
  - python
