channel_targets:
  - tudat-team test
channel_sources:
  - tudat-team/label/test, tudat-team, conda-forge, defaults
boost_cpp:
  - 1.84.0
python:
  - 3.10
  - 3.11
  - 3.12
  - 3.13
python_impl:
  - cpython
  - cpython
  - cpython
numpy:
  - 1.26.*
  - 1.26.*
  - 1.26.*
is_python_min:
  - 3.10
  - 3.11
  - 3.12
  - 3.13
c_compiler:
  - clang
c_compiler_version:
  - 18
cxx_compiler:
  - clangxx
cxx_compiler_version:
  - 18
