{% set name = "tudatpy" %}
  {% set version = "1.0.0" %}
  {% set build = "1" %}
  {% set git_rev = "v" + version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/tudat-team/tudatpy.git
  git_rev: {{ git_rev }}

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
  number: {{ build }}
  run_exports:
    - {{ pin_compatible('cspice-cmake', max_pin='x.x') }}
    - {{ pin_compatible('tudat-resources', max_pin='x.x') }}
    - {{ pin_compatible('nrlmsise-00', max_pin='x.x') }}
    - {{ pin_compatible('sofa-cmake', max_pin='x.x') }}
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}


requirements:
  build:
    # Compilers and build tools
    - {{ compiler('cxx') }}    # [not win]
    - {{ compiler('c') }}      # [not win]
    - {{ compiler('clang') }}  # [win]
    - cmake
    - make  # [unix]

    # Cross-compilation helpers (only needed when build != host platform)
    - python        # [build_platform != target_platform]
    - pip           # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy         # [build_platform != target_platform]
    - pybind11 # [build_platform != target_platform]

    # Boost needed at build for linking
    - boost-cpp {{ boost_cpp }}

  host:
    # Libraries we compile/link against (target platform)
    - tudat-resources
    - cspice-cmake
    - nrlmsise-00
    - sofa-cmake
    - python
    - pip
    - eigen
    - pybind11
    - boost-cpp {{ boost_cpp }}
    - {{ pin_compatible('numpy') }}

  run:
    # Python libraries needed at runtime
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('pandas') }}
    - {{ pin_compatible('scipy') }}
    - {{ pin_compatible('spiceypy') }}
    - {{ pin_compatible('tabulate') }}
    - {{ pin_compatible('matplotlib') }}
    - python
    - astroquery
    - astropy
    - astropy-healpix
    - colorama
    - tqdm
    - nrlmsise-00
    - cspice-cmake
    - sofa-cmake
    - tudat-resources
    - boost-cpp {{ boost_cpp }}

test:
  imports:
    - tudatpy
    - tudatpy.math
    - tudatpy.math.interpolators
    - tudatpy.math.numerical_integrators
    - tudatpy.math.root_finders
    - tudatpy.interface
    - tudatpy.interface.spice
    - tudatpy.astro
    - tudatpy.astro.frame_conversion
    - tudatpy.astro.element_conversion
    - tudatpy.astro.gravitation
    - tudatpy.astro.two_body_dynamics
    - tudatpy.constants
    - tudatpy.numerical_simulation
    - tudatpy.numerical_simulation.environment_setup
    - tudatpy.numerical_simulation.propagation_setup
    - tudatpy.numerical_simulation.estimation_setup
    - tudatpy.plotting
    - tudatpy.util
    - tudatpy.data

  requires:
    - pytest
  source_files:
    - tests/test_tudatpy/test_constants.py
    - tests/test_tudatpy/test_data_biases.py
    - tests/test_tudatpy/test_data_horizons.py
    - tests/test_tudatpy/test_data_mpc.py
    - tests/test_tudatpy/test_data_weights.py
    - tests/test_tudatpy/test_processTrk234.py
    - tests/test_tudatpy/test_data.py
    - tests/test_tudatpy/test_dependent_variable_dictionary.py
    #- tests/test_tudatpy/test_dse_functions.py
    - tests/test_tudatpy/test_interface_spice.py
    - tests/test_tudatpy/test_time_conversions.py
   # - tests/test_imports.py
    # - tests/test_perturbed_orbit.py

  commands:
    - pip install astroquery==0.4.8.dev9321
    - python -c "from tudatpy.data import get_resource_path; print(get_resource_path())"
    - python -c "from tudatpy.data import save2txt"
    #- python -c "from tudatpy.apps.satellite_propagator import single; single()"
    - python -m pytest -v tests/test_tudatpy/test_constants.py
    - python -m pytest -v tests/test_tudatpy/test_data.py
    - python -m pytest -v tests/test_tudatpy/test_time_conversions.py
    - python -m pytest -v tests/test_tudatpy/test_dependent_variable_dictionary.py
    - python -m pytest -v tests/test_tudatpy/test_data_mpc.py
    - python -m pytest -v tests/test_tudatpy/test_data_horizons.py
    - python -m pytest -v tests/test_tudatpy/test_data_biases.py
    - python -m pytest -v tests/test_tudatpy/test_data_weights.py
    - python -m pytest -v tests/test_tudatpy/test_processTrk234.py
    #- python -m pytest -v tests/test_tudatpy/test_dse_functions.py
    # - python -m pytest -v tests/test_perturbed_orbit.py
    # - python -m pytest -v tests/test_imports.py
about:
  home: https://tudat-space.readthedocs.io/
  license: BSD
  license_family: BSD
  summary: A Python platform to perform astrodynamics and space research.

extra:
  recipe-maintainers:
    - geoffreygarrett
