name: .github/workflows/autorerender.yml

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
 check-comments:
   runs-on: [ubuntu-latest]
   if: contains(github.event.comment.body, '/rerender') 
   steps:
   - uses: actions/checkout@v2
   - name: Set up Python 3.8
     uses: actions/setup-python@v2
     with:
       python-version: 3.8
   - name: Add conda to system path
     run: |
       # $CONDA is an environment variable pointing to the root of the miniconda directory
       echo $CONDA/bin >> $GITHUB_PATH
   - name: Enter root directory
     run: |
       cd ${GITHUB_WORKSPACE}
   - name: Ensure conda updated
     run: |
       conda update conda
   - name: Update conda
     run: |
       conda install -n root -c conda-forge conda-smithy
   - name: Rerender feedstock
     run: |
       git config user.name "${GITHUB_ACTOR}"
       git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
       conda smithy rerender -c auto
       git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
   - uses: martialonline/workflow-status@v2
     if: always()
     id: check
   - name: Check workflow failure
     if: always() && steps.check.outputs.status == 'failure'
     run: |
       echo "MESSAGE=rerender workflow failed ([see log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))..." >> "$GITHUB_ENV"
   - name: Check workflow cancelled
     if: always() && steps.check.outputs.status == 'cancelled'
     run: |
       echo "MESSAGE=rerender workflow was cancelled! ([see log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))" >> "$GITHUB_ENV"
   - name: Check workflow success
     if: steps.check.outputs.status == 'success'
     run: |
       echo "MESSAGE=rerender workflow was successful! :tada: ([see log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}))" >> "$GITHUB_ENV"
   - uses: actions-ecosystem/action-create-comment@v1
     if: always()
     with:
       github_token: ${{ secrets.github_token }}
       body: |
         Hello, @${{ github.actor }}! The ${{ env.MESSAGE }}
